import { Header } from './components/Header'
import './globals.css'
import { Providers } from './Providers'

export const metadata = {
  title: 'IMBD Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
